### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Enmton** [3a1/CS2-UEFI-Arduino#1]
Hey, 
how is the memory.efi?
windows system.
build with sln?

**Comment by 3a1** [comment]
Okay I understand your problem
write me on telegram i will send you compiled file
https://t.me/ZebraEth

**Comment by 3a1** [comment]
For all others who also had this issue, google how to compile makefile under windows, use vm, or i will later attach link to the compiled binaries ready for c+p to usb drive
