### ISSUE TITLE
New offset 13997

### ISSUE THREAD

**Issue by NevaYue** [3a1/CS2-UEFI-Arduino#3]
```
#pragma once
#include <sstream>

namespace offsets { // client.dll
    constexpr std::ptrdiff_t dwEntityList = 0x18C2D58;
    constexpr std::ptrdiff_t dwLocalPlayerPawn = 0x17371A8;
    constexpr std::ptrdiff_t dwViewMatrix = 0x19241A0;
    constexpr std::ptrdiff_t dwViewAngles = 0x19309B0;

    constexpr std::ptrdiff_t m_iIDEntIndex = 0x15A4;

    constexpr std::ptrdiff_t m_vecViewOffset = 0xC58;
    constexpr std::ptrdiff_t m_hPlayerPawn = 0x7E4;
    constexpr std::ptrdiff_t m_lifeState = 0x338;
    constexpr std::ptrdiff_t m_iTeamNum = 0x3CB;
    constexpr std::ptrdiff_t m_vOldOrigin = 0x127C;
    constexpr std::ptrdiff_t m_iHealth = 0x334;
    constexpr std::ptrdiff_t m_vecOrigin = 0x550;

}``
```

**Comment by NevaYue** [comment]
I think i cant use it by Leonardo in CS2.I want to check if it solve?

**Comment by NevaYue** [comment]
![619e709cb703d32d8415ea32c1ebfd16](https://github.com/3a1/CS2-UEFI-Arduino/assets/102574946/09f0af5c-c33b-4528-ba07-db2cc1bf3eba)
I update offset i check if i set Arduino model  it doesnt work
if i start without arduino it work. how I solve it bro

**Comment by 3a1** [comment]
send screenshot what is showing in the console output with arduino

**Comment by NevaYue** [comment]
How to do that?
![image](https://github.com/3a1/CS2-UEFI-Arduino/assets/102574946/d3c7dcf6-b66a-49a6-b36f-eb17bf44853f)

**Comment by NevaYue** [comment]
Nothing is showing in the sonsole output

**Comment by NevaYue** [comment]
i contact your telegram
